package com.flowershopping.entity;
// Generated 2016-9-6 20:01:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.apache.struts2.json.annotations.JSON;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private static final long serialVersionUID = 8321617459373908027L;
	private Integer id;
	private String categoryName;
	@SuppressWarnings("rawtypes")
	private Set goodses = new HashSet(0);

	public Category() {
	}

	public Category(int id) {
		this.id = id;
	}

	public Category(String categoryName) {
		this.categoryName = categoryName;
	}

	@SuppressWarnings("rawtypes")
	public Category(String categoryName, Set goodses) {
		this.categoryName = categoryName;
		this.goodses = goodses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@JSON(serialize = false)
	@SuppressWarnings("rawtypes")
	public Set getGoodses() {
		return this.goodses;
	}

	@SuppressWarnings("rawtypes")
	public void setGoodses(Set goodses) {
		this.goodses = goodses;
	}

}
