package com.flowershopping.entity;
// Generated 2016-9-6 20:01:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

	private static final long serialVersionUID = -3666662289931076525L;
	private Integer id;
	private Category category;
	private String goodsName;
	private String description;
	private BigDecimal price;
	private String imgUrl;

	public Goods() {
	}

	public Goods(Category category, String goodsName, BigDecimal price) {
		this.category = category;
		this.goodsName = goodsName;
		this.price = price;
	}

	public Goods(Category category, String goodsName, String description, BigDecimal price, String imgUrl) {
		this.category = category;
		this.goodsName = goodsName;
		this.description = description;
		this.price = price;
		this.imgUrl = imgUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

}
