package com.flowershopping.entity;
// Generated 2016-9-6 20:01:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Ordersdetails generated by hbm2java
 */
public class Ordersdetails implements java.io.Serializable {

	private static final long serialVersionUID = 3588732686916111521L;
	private Integer id;
	private Orders orders;
	private String goodsName;
	private BigDecimal price;
	private int num;

	public Ordersdetails() {
	}

	public Ordersdetails(Orders orders, String goodsName, BigDecimal price, int num) {
		this.orders = orders;
		this.goodsName = goodsName;
		this.price = price;
		this.num = num;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

}
